
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Compilador de optimizaci贸n de C/C++ de Microsoft (R) versi贸n 19.37.32824 para x64
      (C) Microsoft Corporation. Todos los derechos reservados.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.37.32824.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/jared/OneDrive/Escritorio/Escuela/Tercer Semestre/Progra III/Progra_3_Angel_Osornoo/Documentacion de un arbol/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Nota: inclusi贸n del archivo: C:\\Users\\jared\\OneDrive\\Escritorio\\Escuela\\Tercer Semestre\\Progra III\\Progra_3_Angel_Osornoo\\Documentacion de un arbol\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Nota: inclusi贸n del archivo: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/jared/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/jared/OneDrive/Escritorio/Escuela/Tercer Semestre/Progra III/Progra_3_Angel_Osornoo/Documentacion de un arbol/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rwal3d"
      binary: "C:/Users/jared/OneDrive/Escritorio/Escuela/Tercer Semestre/Progra III/Progra_3_Angel_Osornoo/Documentacion de un arbol/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rwal3d"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/jared/OneDrive/Escritorio/Escuela/Tercer Semestre/Progra III/Progra_3_Angel_Osornoo/Documentacion de un arbol/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-rwal3d
        
        Run Build Command(s):C:/Users/jared/AppData/Local/Programs/CLion/bin/ninja/win/x64/ninja.exe -v cmTC_30395 && [1/2] C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Ob0 /Od /RTC1 -MDd -Zi /showIncludes /FoCMakeFiles\\cmTC_30395.dir\\CMakeCCompilerABI.c.obj /FdCMakeFiles\\cmTC_30395.dir\\ /FS -c C:\\Users\\jared\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c
        [2/2] cmd.exe /C "cd . && C:\\Users\\jared\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E vs_link_exe --intdir=CMakeFiles\\cmTC_30395.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1437~1.328\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_30395.dir\\CMakeCCompilerABI.c.obj  /out:cmTC_30395.exe /implib:cmTC_30395.lib /pdb:cmTC_30395.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
...
